### ISSUE TITLE
some commit messages from contributors are uninformative and so they slow the entire team down when identifying a changeset

### ISSUE THREAD

**Issue by TimDaub** [neume-network/documents#13]
- sometimes contributors call their commit messages "fix" and then it contains actually an entire changeset for important fixes
- it's important to us to identify commits by their message as we have to sometimes look something up or revert a thing
- so it'd be ideal if commit messages would always contain a nice summary of what's happening within the changeset
- but we can also not ask a CI to validate commit messages as a machine can't tell if a commit message is a nice description or some blank-filler statement

**Comment by djfnd** [comment]
Is there anything that we can change from a process perspective to help with this issue?
