### ISSUE TITLE
Address architecture proposal conflict in social architecture process

### ISSUE THREAD

**Issue by TimDaub** [neume-network/documents#5]
@il3ven and I do have different opinions when it comes to the strategies architecture:

- @il3ven's proposal: https://github.com/neume-network/strategies/issues/49
- vs. the architecture, I'm currently implementing in the strategies repo.

Conflict:

- @il3ven's point is that it's hard to understand for an outsider that there's e.g. a convention to e.g. pass `return { write: "string" }`
- My point is that e.g. currently we can't focus on improving aesthetics because we have to ship for e.g. Hifilab's music-os.
- Another one of my points is that e.g. a code's correctness trumps its interface's aesthetic.

Partially, some of those values are already present in the [social architecture](https://github.com/neume-network/documents/blob/main/social-architecture.md). For e.g. we say that:

> Simplicity: A design must be simple, both in implementation and interface. It is more important for the interface to be simple than the implementation [4].

> Correctness: A design must be correct in all observable aspects. Incorrectness is simply not allowed

> Consistency: The design must not be overly inconsistent. Consistency can be sacrificed for simplicity in some cases [4].

So e.g. I'm rejecting @il3ven's proposal on the following points:

- The current architecture in the main branch works. It is correct - that's the most important thing about the implementation
- It's unclear if @il3ven's proposal will be correct too, e.g. check `once` function comment
- Finally; we're ok with compromising on consistency for simplicity. We're not OK with compromising simplicity for correctness.

IMO, I've validly represented the guidelines in the social architecture document. @il3ven would you agree that I've validly represented them? If yes, do you think these social architecture principles reflect your preferences for creating software? How could we improve them to include your principles too?

Additionally, there's #6

**Comment by il3ven** [comment]
> would you agree that I've validly represented them

Yes, the social architecture correctly captures the guidelines. I agree on the guidelines. 😅

**Comment by TimDaub** [comment]
fine, then I'm closing
